<?xml version="1.0"?>
<robot name="advanrobot_antenna" xmlns:xacro="http://ros.org/wiki/xacro">
	
  <!-- Import all available sensors -->
  <!-- xacro:include filename="$(find rb1_base_description)/urdf/sensors/all_sensors.urdf.xacro" / --> 	
	
  <xacro:macro name="advanrobot_antenna" params="name parent *origin">
    
    <!-- ANTENNA -->
    <link name="${name}_link">
    <inertial>
      <!-- mass value="16.0" / -->
      <mass value="1.0" />
      <origin xyz="0 0 0" />
      <!-- inertia  ixx="1.0" ixy="0.0"  ixz="0.0"  iyy="1.0"  iyz="0.0"  izz="1.0" / -->
      <inertia  ixx="0.1" ixy="0.0"  ixz="0.0"  iyy="0.1"  iyz="0.0"  izz="0.1" />
    </inertial>
    <visual>
       <origin xyz="0 0 0" rpy="0 0 0" />
       <geometry>
	     <mesh filename="package://advanrobot_description/meshes/antennas/adrb_simplified.dae"/>
       </geometry>
       <material name="darkgrey">
         <color rgba="0.1 0.1 0.1 1"/>
       </material>
    </visual>  
    <collision>
       <origin xyz="0 0 0" rpy="0 0 0 " />
       <geometry>
         <mesh filename="package://advanrobot_description/meshes/antennas/adrb_simplified.dae"/>
       </geometry>
    </collision>
  </link>
  <joint name="${name}_joint" type="fixed">
      <insert_block name="origin"/>
<!--
      <origin xyz="0 0 0.258" rpy="1.5708 0 0" />
       <origin xyz="0 0 ${wheel_radius - wheel_offset_z}" rpy="0 0 0" />
-->
      <parent link="${parent}"/>
      <child link="${name}_link" />
    </joint>
    
    

    
  </xacro:macro>
  
  
</robot>
