controller_frequency: 20
planner_patience: 10
controller_patience: 10.0
shutdown_costmaps: false
oscillation_timeout: 0.0
oscillation_distance: 0.5
planner_frequency: 0.04

global_costmap:
    robot_radius: 0.25
    global_frame: /map
    robot_base_frame: /base_footprint
    plugins:
      - {name: static_map_layer, type: "costmap_2d::StaticLayer"}
      - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
      - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
    static_map_layer:
      static_map: true
    obstacle_layer:
      observation_sources: hokuyo_laser camera_front
      hokuyo_laser: {sensor_frame: hokuyo_laser_link,
                     data_type: LaserScan,
                     topic: /hokuyo/scan,
                     marking: true,
                     clearing: true,
                     observation_persistence: 0.0,
                     inf_is_valid: true,
                     obstacle_range: 8.0,
                     raytrace_range: 8.0
                    }
    camera_front: {sensor_frame: camera_front_cam_depth_optical_frame,
                     topic: /camera_front/depth/points,
                     data_type: PointCloud2,
                     expected_update_rate: 2.0,
                     observation_persistence: 0.0,
                     marking: true,
                     clearing: true,
                     min_obstacle_height: 0.0,
                     max_obstacle_height: 2.0,
                     obstacle_range: 2.15,
                     raytrace_range: 2.15
                    }
    inflation_layer:
      inflation_radius: 0.40
      cost_scaling_factor: 10.0

local_costmap:
    robot_radius: 0.25
    global_frame: /odom
    robot_base_frame: /base_footprint
    update_frequency: 2.0
    publish_frequency: 2.0
    rolling_window: true
    width: 4.0
    height: 4.0
    plugins:
      - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
      - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    obstacle_layer:
      observation_sources: hokuyo_laser camera_front
      hokuyo_laser: {sensor_frame: hokuyo_laser_link,
                     data_type: LaserScan,
                     topic: /hokuyo/scan,
                     marking: true,
                     clearing: true,
                     observation_persistence: 0.0,
                     inf_is_valid: true,
                     obstacle_range: 8.00,
                     raytrace_range: 8.00
                    }
      camera_front: {sensor_frame: camera_front_cam_depth_optical_frame,
                     topic: /camera_front/depth/points,
                     data_type: PointCloud2,
                     expected_update_rate: 2.0,
                     observation_persistence: 0.0,
                     marking: true,
                     clearing: true,
                     min_obstacle_height: 0.0,
                     max_obstacle_height: 2.00,
                     obstacle_range: 2.15,
                     raytrace_range: 2.15
                    }
    obstacle_layer_cam:
      observation_sources: camera_front
    inflation_layer:
      inflation_radius: 0.02
      cost_scaling_factor: 10.0
